export default {
  text: {
    add: 'Add',
    addLeadButton: 'Add Lead',
    addCouponSuccess: 'Add Coupon Successfully',
    alertLeadId: 'Your lead with lead ID {{leadId}} was created',
    addLead: 'Add lead',
    autoAssign: 'Auto assign',
    agentLead: 'Agent/Lead',
    agentScore: 'Agent score',
    assign: 'assign',
    assignedTo: 'Assigned to',
    assignedToUser: 'Assigned to user',
    assignedToTeam: 'Assigned to team',
    assignedOrderSuccess: 'Assigned order successfully',
    assignedOrderFailed: 'Assigned order failed',
    unassignedOrderSuccess: 'Unassigned order successfully',
    unassignedOrderFailed: 'Unassigned order failed',
    addAddressSuccessful: 'Address added successfully',
    addPhoneTitle: 'Add new phone number',
    addButton: 'Add',
    address: 'Address',
    addressUseMultiple: 'Address Use (Multiple select)',
    addressType: 'Address type',
    appointment: 'Appointment',
    appointmentBtn: 'Appointment',
    appointmentDate: 'Appointment date',
    apply: 'Apply',
    addNewAddress: 'Add new address',
    addNewEmailAddress: 'Add new email address',
    addUser: 'Add User',
    addUserToTeamFail: 'User created but failed to add to team',
    activate: 'Activate',
    activateUserSuccess: 'Activation user successfully',
    activateUserFailed: 'Activation user failed',
    agent: 'Agent',
    addEmailSuccess: 'Add Email Successfully',
    addPhoneSuccess: 'Add phone number successfully',
    age: 'Age',
    agentName: 'Agent name',
    addLeadSuccess: 'Create Lead Successfully',
    addCoupon: 'Add Coupon',
    assignOn: 'Assigned on',
    appointmentType: 'Appointment Type *',
    billing: 'Billing',
    bulkImportantSuccess: 'Star has been successfully added to your leads',
    bulkUnimportantSuccess:
      'Star has been successfully removed from your leads',
    cancelButton: 'Cancel',
    confirmImport: 'Confirm Import',
    confirmButton: 'Confirm',
    createTeam: 'Create Team',
    closeButton: 'Close',
    createBy: 'Created by',
    createOn: 'Create On',
    createUser: 'Create User',
    clearAll: 'Clear All',
    createSource: 'Create Source',
    companyName: 'Company name',
    company: 'Company',
    carBrand: 'Car Brand',
    carDashcam: 'Car dashcam',
    carEngineSize: 'Car engine size',
    carModel: 'Car Model',
    carModification: 'Car Modification',
    carRegisteredProvince: 'Car Registered Province',
    carYear: 'Car Year',
    carTransmission: 'Car transmission',
    carUsage: 'Car usage',
    createAdminTeam: 'Create Admin Team',
    create: 'Create',
    createTeamSuccess: 'Create Team Successfully',
    createTeamFail: 'Create Team Fail',
    createUserSuccessfully: 'User created successfully',
    createUserFail: 'Error creating user: {{message}}',
    createOrderSuccess: 'Create Order Successfully',
    creteOrderFail: 'Create Order Fail',
    callErrorMessage: 'There are no calls for this lead',
    callInProgressMessage: 'Call currently in progress',
    changeStatus: 'Change Status',
    updateUserSuccessfully: 'User updated successfully',
    updateUserFail: 'Error updating user: {{message}}',
    updateTeamSuccessfully: 'Update Team Successfully',
    updateTeamFail: 'Update Team Fail',
    createLeadSourceSuccessfully: 'Lead Sources created successfully',
    createLeadSourceFail: 'Error creating lead sources: {{message}}',
    createLeadSourceScoreFail:
      'Source Created but error saving the score, please edit and try again',
    createRejectionSuccessfully: 'Lead rejection created successfully',
    updateRejectionSuccessfully: 'Lead status changed successfully',
    createRejectionFail: 'Error creating Lead rejection: {{message}}',
    currentInsurer: 'Current insurer',
    connectedCall: 'Connected Call',
    connectDials: 'Connect dials',
    cc: 'Cc',
    content: 'Content',
    comment: 'Comment',
    call: 'Call',
    campaign: 'Campaign',
    createAppointmentSuccess: 'Create Appointment Successfully',
    createdOn: 'Created on',
    communicationType: 'Communication type',
    copiedRecoveryLinkToClipboard:
      'Recovery Link copied to Clipboard. This link can be used only once',
    coupon: 'Coupon',
    couponCode: 'Coupon Code',
    couponDiscount: 'Coupon Discount',
    couponValidateMessage: 'The lead is in PURCHASE status',
    customer: 'Customer',
    customerId: 'Customer ID',
    customerAgreed: 'Customer Agreed',
    customerRequested: 'Customer Requested',
    createNewCustomer: 'Create New Customer',
    confirmCustomer: 'Confirm Customer',
    cantConfirmNow: `Can't Confirm Now`,
    confirmToCreateCustomer: 'Confirm to create a new customer',
    connectLeadToCustomer:
      'Connect this lead to the customer profile found in the system',
    confirmData: 'Confirm data',
    customerProfile: 'Customer profile',
    dragDropFileOrChooseFile: 'Drag and drop file here or choose file',
    dropFilesHere: 'Drop the files here',
    dragOrDropFile: 'Drag or drop some files here or',
    chooseFile: 'choose file',
    district: 'District',
    date: 'Date',
    datePresets: 'Date presets',
    dailyLimit: 'Daily Lead Limit',
    dob: 'DOB',
    unassign: 'unassign',
    unassigned: 'Unassigned',
    unDeleteUserSuccessfully: 'Undelete User Successfully',
    unDeleteUserFailed: 'Undelete User Failed',
    createLeadFail: 'Create Lead Fail',
    dataIsUnavailable: 'Data is unavailable',
    deleteCouponModal: 'Do you want to remove coupon code?',
    deleteDocumentModal: 'Do you want to delete {{type}} file?',
    doYouWantTo: 'Do you want to',
    orderAssign: 'order',
    ordersAssign: 'orders',
    leadAssign: 'lead',
    leadsAssign: 'leads',
    deleteCouponSuccess: 'Remove Coupon Successfully',
    editTeam: 'Edit Team',
    enable: 'Enable',
    editUser: 'Edit user',
    email: 'Email',
    emptyFile: 'File is empty',
    editAdminTeam: 'Edit Admin Team',
    entries: 'entries',
    editNewLeadSuccess: 'Update Lead Successfully',
    editRetainerLeadSuccess: 'Update Lead Successfully',
    editNewLeadFail: 'Error Updating Lead: {{message}}',
    editRetainerLeadFail: 'Error Updating Lead: {{message}}',
    errorGettingRecoveryLink: 'Error generating Recovery Link',
    expiryDate: 'Expiry date',
    emailTemplate: 'Email Template',
    emailMessageUpdatedSuccess: 'Email message updated successfully',
    enterSubject: 'Enter a subject',
    enterMessage: 'Enter a message',
    enterCC: 'Enter cc',
    enterFullName: 'Enter a full name',
    enterFirstName: 'Enter a first name',
    enterLastName: 'Enter a last name',
    enterAddress: 'Enter an address',
    enterCompanyName: 'Enter a company name',
    enterTaxId: 'Enter a tax ID',
    enterPhoneNumber: 'Enter a phone number',
    enterPaymentAmount: 'Enter payment amount',
    enterPaymentDate: 'Enter payment date',
    enterAppointmentDate: 'DD/MM/YYYY',
    enterEmail: 'Enter an email',
    enterCoupon: 'Enter a coupon code',
    errorMessage: 'Error: {{message}}',
    existingInformation: 'Existing Information',
    failedDials: 'Failed dials',
    female: 'Female',
    fieldMismatch: 'Field mismatch',
    fileName: 'File name:',
    firstName: 'First name',
    firstNameAsterisk: 'First name *',
    fullName: 'Full name',
    first: 'First',
    free: 'Free',
    fileSizeLimit:
      'File {{fileName}} was rejected. File is too big. Size limit is 1 megabytes.',
    from: 'From',
    followup: 'Followup',
    forward: 'Forward',
    gender: 'Gender',
    gitVersion: 'Version',
    gitVersionUnknown: '<unknown>',
    goToHomePage: 'GO TO HOMEPAGE',
    hide: 'Hide',
    hangUp: 'Hang up',
    instruction1: '1. At least 8 characters.',
    instruction2: '2. A mixture of both uppercase and lowercase letters.',
    instruction3: '3. A mixture of letters (a-z), (A-Z) and numbers (0-9).',
    instruction4:
      '4. Inclusion of at least one special character, e.g., !  @ # ? ] ! $ % ^ & * ( ) / \\ ',
    importCarDiscountFile: 'Import car discount file',
    importCarDiscountFileInProgress: 'Import car discount file is in progress',
    importCSVSuccess: 'Import CSV successful',
    importCSVFailed: 'Import Failed',
    importPackages: 'Import standard packages',
    importPackagesProgress: 'Import package is in progress',
    importRenewPackages: 'Import renewal packages',
    importLead: 'Import lead',
    importStatus: 'Import Status',
    importDate: 'Import Date',
    importedBy: 'Imported By',
    importedOn: 'Imported On',
    importedUser: 'Import User',
    importFile: 'Import File',
    insurer: 'Insurers',
    installment: '{{installmentNumber}} time',
    installments: '{{installmentNumber}} installments',
    invalidCoupon: 'Invalid coupon code',
    invalidDataFormat: 'Please enter valid data for {{column}} of row {{row}}',
    invalidEmail: '{{email}} is not a valid email address.',
    invalidEmail2: 'Invalid Email',
    invalidRabbitEmail: '{{email}} is not a rabbit email address.',
    isExistedEmail: '{{email}} has already been added.',
    input: 'Input',
    inputName: 'Input Name',
    inputUser: 'Input User',
    importUserFail: 'Import User Fail',
    invalidDateSearch: 'Please select today or a later date !',
    invalidSundaySearch: 'Appointments on Sundays are not allowed !',
    invalidDateWithCurrent: 'Date must be after “current date”',
    invalidDateFromCurrent:
      'Date must be before “current date + {{month}} months”',
    inputFirstNameValid: 'Please enter a valid first name',
    inputLastNameValid: 'Please enter a valid last name',
    inputMaxLength: 'May not be greater than {{length}} characters.',
    inputInvalid: 'Field input is invalid',
    kb: 'KB',
    lastVisitedOn: 'Last visited on',
    leadSetting: 'Lead Setting',
    loginSuccess: 'Login Success',
    loginFailed: 'Login Failed!',
    logout: 'Logout',
    leadCount: 'Lead Count',
    leadFound: 'We have found {{count}} lead',
    leadFound_plural: 'We have found {{count}} leads',
    lastLoginOn: 'Last Login On',
    lastName: 'Last Name',
    lastNameAsterisk: 'Last Name *',
    lastInsurer: 'Last Insurer',
    lastPremium: 'Last Premium',
    leadAge: 'Lead Age',
    leadSource: 'Lead Source',
    leadInformation: 'Lead information',
    latestInformation: 'Latest Information',
    paymentStatus: 'Payment status',
    paymentDaysOverdue: 'Payment days overdue',
    documentStatus: 'Document Status',
    qcStatus: 'QC Status',
    pleaseChooseCorrectCustomer:
      'Please choose the correct customer information',
    submissionStatus: 'Submission Status',
    approvalStatus: 'Approval Status',
    complete: 'Complete',
    approved: 'Approved',
    partiallyFailed: 'Partially Failed',
    partiallyRejected: 'Partially Rejected',
    rejected: 'Rejected',
    submitted: 'Submitted',
    leadSourceAsterisk: 'Lead Source *',
    leadType: 'Lead Type',
    leadPriority: 'Lead/Priority',
    lead: 'Lead {{number}}',
    leadId: 'Lead ID',
    leadRecord: 'Lead Record',
    leadStatus: 'Lead Status',
    leadScore: 'Lead Score',
    logoutSuccess: 'Logout User Successfully',
    logoutFailed: 'Error Logout User: {{message}}',
    loading: 'Loading...',
    lifeTime: 'Life Time',
    licensePlate: 'License plate',
    leadMaxRecord: 'Paging limit reached. Please use filters.',
    latestCustomer: 'Latest customer',
    mandatory: 'Mandatory',
    manager: 'Manager',
    missingHeaderFile: 'Invalid file, missing headers',
    min: 'min',
    message: 'Message',
    male: 'Male',
    markImportant: 'Mark Important',
    markUnimportant: 'Mark Unimportant',
    medium: 'Medium',
    minimum: 'Minimum',
    maximum: 'Maximum',
    maximumUpload: 'The maximum upload for {{type}} is {{maxNumber}}',
    marketingConsent: 'Marketing Consent',
    mailboxCommunications: 'Mailbox Communications',
    miss: 'Miss',
    mr: 'Mr',
    mrs: 'Mrs',
    myBestGuess: 'My Best Guess',
    nationalIdPassport: 'National ID / passport',
    customerPolicyholder: 'Customer / Policyholder',
    new: 'New',
    newLead: 'New Lead',
    newLeads: 'New Leads',
    no: 'No',
    numberOfPackages: 'no. Of packages',
    noDots: 'No.',
    name: 'Name',
    newMessage: 'New Message',
    noData: 'No data',
    networkError: 'Network error',
    netPremium: 'Net Premium',
    orderStatus: 'Order Status',
    overFlowError:
      'You cannot save if two (or more) of the options are set to the same number.',
    other: 'Other',
    paymentType: 'Payment type',
    paymentTerms: 'Payment terms',
    passedBookingTime: 'Booking time was pass !',
    passwordError:
      'Your password is in incorrect format. Please set your password according to the provided guideline below.',
    preferredInsurer: 'Preferred insurer',
    preferredType: 'Preferred v. type',
    premiumBeforeDiscount: 'Premium before discount',
    phone: 'Phone',
    phoneAsterisk: 'Phone *',
    product: 'Product',
    productType: 'Product Type',
    phoneNumber: 'Phone number',
    packageType: 'Package type',
    paymentCall: 'Payment call',
    priceAfterDiscount: 'Price after discount',
    priority: 'Priority {{role}}',
    province: 'Province',
    postcode: 'Postcode',
    policy: 'Policy',
    policyholder: 'Policyholder',
    policyId: 'Policy ID',
    insuranceCategory: 'Insurance Category',
    policies: 'Policies',
    policyStartDate: 'Policy start date',
    policyStartingDate: 'Policy starting date',
    policyPreferredType: 'Policy preferred type',
    personal: 'Personal',
    placeHolderCc:
      'Type or paste rabbit finance email addresses and press "Enter or Tab"',
    pushCommentSuccess: 'Push comment successfully',
    leftComment: '{{name}} left a comment',
    systemUser: 'System',
    paymentConfirmation: 'Payment Confirmation',
    paymentAmount: 'Payment Amount (THB)',
    paymentDate: 'Payment Date',
    paymentSchedule: 'Payment schedule',
    pleaseSelect: 'Please select',
    permissionDenied: "You don't have the permissions to access this resource",
    paymentAmountRequired: 'Payment amount is required !',
    paymentDateRequired: 'Payment date is required !',
    packageNotFound: 'Package not found !',
    policyHolderInformation: 'Policy holder information',
    inputSumInsuredError:
      'Please input max {{label}} greater than min {{label}}',
    quoteFollowUp: 'Quote follow up',
    quotesAndPackageURL: 'Quotes & Package URL',
    requiredMinMax: 'Please input both max and min {{label}}',
    requiredCsvValidation: 'CSV File only !',
    requiredColumnValidation: 'Column {{column}} is missing',
    requiredRowsValidation: '{{name}} row {{row}} is missing {{column}}',
    requiredFirstName: 'First name is a required field',
    requiredLastName: 'Last name is a required field',
    requiredPhone: 'Phone is a required field',
    required: 'required',
    retainer: 'Retainer',
    retainerLead: 'Retainer Lead',
    retainerLeads: 'Retainer leads',
    renewal: 'Renewal',
    renewalLead: 'Renewal Lead',
    renewalId: 'Renewal ID',
    referenceId: 'Reference ID',
    requestCustomQuote: 'CREATE CUSTOM QUOTE',
    addPayslip: 'Add Payslip',
    recoveryLink: 'Recovery Link',
    rejectLead: 'Reject',
    rejectionReason: 'Rejection Reason',
    replyAll: 'Reply all',
    reply: 'Reply',
    replyMessage: 'Reply Message',
    search: 'Search',
    selectFiles: 'Drag or click to select files',
    downloadFiles: 'Download {{count}} files',
    download: 'Download',
    remove: 'Remove',
    searchResults: 'Search Result: {{results}} Results',
    settings: 'Settings',
    selectAppointmentTypes: 'Select appointment types',
    selectUsers: 'Select Users',
    supervisor: 'Supervisor',
    scoringError: 'Sum should be equal to 100',
    sequence: 'Sequence',
    source: 'Source',
    score: 'Score',
    status: 'Status',
    suspend: 'Suspend',
    saveButton: 'Save',
    selectDateType: 'Select date type',
    shipment: 'Shipment',
    show: 'Show',
    subTotal: 'Subtotal',
    suspendUserSuccess: 'Suspend user successfully',
    suspendUserFailed: 'Suspend user failed',
    sumInsured: 'Preferred sum insured',
    startDate: 'Start date',
    youngestDriverDob: 'Youngest driver DOB',
    select: 'Select',
    save: 'Save',
    send: 'Send',
    sms: 'SMS',
    subject: 'Subject',
    subjectAsterisk: 'Subject *',
    sum: 'Sum',
    summary: 'Summary',
    sec: 'sec',
    signIn: 'Sign in',
    sumInsuredLabel: 'Sum Insured',
    sendEmailSuccess: 'Send Email Successfully',
    sendSmsSuccess: 'Send Sms Successfully',
    subDistrict: 'Sub District',
    suspendAccount: 'Account has been suspended',
    templateButton: 'Template',
    today: 'Today',
    totalCall: 'Total Call Attempts',
    totalCallDuration: 'Total Call Duration',
    totalNetPremium: 'Total net premium',
    teamName: 'Team Name',
    team: 'Team',
    teamRole: 'Team Role',
    template: 'Template',
    total: 'Total',
    totalDials: 'Total dials',
    taxId: 'Tax ID',
    totalLeadLimit: 'Total Lead Limit',
    to: 'To',
    totalMaxFileSize:
      '{{fileName}} can not be added. Total Size limit is 5 megabytes.',
    transferCall: 'Transfer Call',
    transferCallComplete: 'Transfer completed',
    transfer: 'Transfer',
    type: 'Type',
    updateLeadButton: 'Update lead',
    updateOn: 'Update On',
    userRole: 'User role',
    updateUser: 'Update User',
    updateSource: 'Update Source',
    updateTeam: 'Update Team',
    userFound: '{{count}} {{user}} to be updated',
    user: 'User',
    userCount: 'User count',
    userName: 'Username',
    update: 'Update',
    unnecessaryRowsValidation:
      '{{name}} row {{row}} has unnecessary field {{column}}',
    unverified: 'unverified',
    urgent: 'Urgent',
    urgentCall: 'Urgent call',
    updateNewLeadSuccess: 'Update New Lead Successfully',
    updateRetainerLeadSuccess: 'Update Retainer Lead Successfully',
    updateNewLeadFailed: 'Error Updating New Lead: {{message}}',
    updateRetainerLeadFailed: 'Error Updating Retainer Lead: {{message}}',
    updateLeadSourceSuccessfully: 'Lead Sources updated successfully',
    updateLeadSourceFail: 'Error updating lead sources: {{message}}',
    unsupportedFile:
      'File {{fileName}} was rejected. File type is not supported.',
    updateLeadSourceScoreFail: 'Error saving the source score',
    updateLeadScoreSuccess: 'Update {{leadType}} Lead Score Successfully',
    updateLeadScoreFailed:
      'Error Updating {{leadType}} Lead Score: {{message}}',
    createDocumentSuccessfully: 'Upload Document Successfully',
    utmMedium: 'UTM medium',
    utmCampaign: 'UTM campaign',
    updateBy: 'Update by',
    updatedOn: 'Updated on',
    uploadAttachmentFail: 'Upload attachment fail',
    updateLeadSuccess: 'Update Lead Successfully',
    updateLeadFail: 'Update Lead Fail',
    valid: 'Valid',
    verified: 'verified',
    landline: 'landline',
    viewQuotes: 'VIEW QUOTES',
    validatePhone: 'Phone number should be 10 digits and start with 0',
    viewRenewal: 'VIEW RENEWAL',
    voiceFile: 'Voice file',
    voucherDiscount: 'Voucher & discounts',
    website: 'Website',
    wrongDocument: 'Wrong Document',
    callDuration: 'Call duration',
    compose: 'COMPOSE',
    noMessageSelected: 'No Message Selected',
    yes: 'Yes',
    viewPurchase: 'View Purchase',
    rowExcelInvalid: 'Row {{row}} {{name}} "{{value}}" is invalid',
    webActivity: 'Web Activity',
    remark: 'Remark',
    minutes: 'minutes',
    minutesAcronym: 'Min',
    vehicle: 'Vehicle',
    typeOfVehicle: 'Type of vehicle',
    chassisNumber: 'Chassis Number',
    searchImportFileName: 'Search by import file name',
    datePickerPlaceholder: 'DD/MM/YYYY - DD/MM/YYYY',
    general: 'General',
    detailPolicy: 'Detail of policy',
    pending: 'Pending',
    deleteDocumentSuccessfully: 'Delete order document successfully.',
    updateOrderSuccessfully: 'Update order successfully',
    updateOrderFailed: 'Error: {{message}}',
    selectAll: 'Select All',
    item: '{{ count }} item',
    items: '{{ count }} items',
  },
  lead: {
    car: 'Car',
    changeCar: 'Change Car',
    activity: 'Activity',
    communication: 'Communication',
    assignment: 'Assignment',
    audit: 'Audit',
    remark: 'Remark',
    comment: 'Comment',
    allActivity: 'All Activity',
    document: 'Document',
  },
  order: {
    sale: 'Sales Info',
    policyholder: 'Policyholder info',
  },
  compound: {
    taxId: 'Tax ID',
  },
  errors: {
    required: '{{field}} is required',
    errorReasons: 'Error because of these:',
    invalidLicense: 'Please provide correct license plate format',
  },
  errorPage: {
    notFoundText:
      'Sorry, the item you are looking for is not on the site anymore',
    backToHomePage: 'Go to Home Page >>',
  },
  appointmentType: {
    requested: 'Requested',
    agreed: 'Agreed',
    assumed: 'Assumed',
    document_follow_up: 'Document follow up',
    wrong_document: 'Wrong document',
  },
  timeSlotCallBack: {
    appointment: 'Appointment',
    appointmentType: 'Appointment type',
    subject: 'Subject',
    customerName: 'Customer name',
    leadID: 'Lead ID',
    orderID: 'Order ID',
    viewMoreButton: 'View more',
  },
  package: {
    importFileName: 'Import File Name',
    requiredFields: 'Required',
    minDate: 'Start Date cannot be earlier than Today Date',
    invalidDateFormat: 'Invalid Date Format',
    expirationDateAndStartDate: 'Expirations cannot be earlier than Start Date',
    createPackageSuccessfully: 'Package created successfully',
    saveAndSendPackageButton: 'Save & Send Package',
    backButton: 'Back',
    packageTitle: 'Package',
    carAndSumInsuredTitle: 'Car And Sum Insured',
    coverageTitle: 'Coverage',
    name: 'Package Name*',
    start_date: 'Start Date*',
    expiration_date: 'Expirations*',
    insurance_company_id: 'Insurance Company*',
    car_insurance_type: 'Insurance Type*',
    oic_code: 'OIC Code*',
    car_repair_type: 'Repair*',
    modified_car_accepted: 'Car Modification Accepted?*',
    has_cctv_discount: 'Is CCTV discount included?*',
    car_age: 'Car age(year)*',
    carAndSumInsured: 'Sum Insured*',
    sum_coverage_min: 'Min',
    sum_coverage_max: 'Sum Insured*',
    deductible_amount: 'Deductible (THB)*',
    price: '<b>Gross premium</b>/price without mandatory (THB)*',
    fire_theft_coverage: 'Theft & fire coverage?*',
    fire_theft_coverage_value: 'Value',
    flood_coverage: 'Flood coverage?*',
    flood_coverage_value: 'Value',
    car_submodels: 'Car Submodels*',
    liability_per_person_coverage: 'Liability for damage per person (THB)*',
    liability_per_accident_coverage: 'Liability for damage per time (THB)*',
    liability_property_coverage: 'Liability for property damage (THB)*',
    personal_accident_coverage: 'Personal Accident (THB)*',
    personal_accident_coverage_no: 'No. of persons PA*',
    medical_expenses_coverage: 'Medical Expenses (THB)*',
    medical_expenses_coverage_no: 'No. of persons ME*',
    bail_bond_coverage: 'Bail Bond (THB)*',
    yes: 'Yes',
    no: 'No',
    garage: 'Garage',
    dealer: 'Dealer',
    stepValidation: 'Must be multiplier of 10,000',
    statusSearchLabel: 'Status',
    insurerSearchLabel: 'Insurer',
    priceSearchLabel: 'Price',
    carBrandSearchLabel: 'Car Brand',
    carModelSearchLabel: 'Car Model',
    subModelSearchLabel: 'Sub Model',
    carAgeSearchLabel: 'Car age',
    provinceSearchLabel: 'Province',
    insuranceTypeSearchLabel: 'Insurance type',
    searchLabel: 'Search',
    downloadPackageAllBtn: ' DOWNLOAD PACKAGE ALL',
    carAgeMinMessage: 'Value can not be 0',
    packages: 'Packages',
    limitTimeSearchPackage: 'Search time greater than 3 minutes',
    package_type: 'Package type*',
    fixedDriver: 'Fixed driver amount',
    firstDriverDOB: '1st driver DOB',
    secondDriverDOB: '2nd driver DOB',
    policyDOBMaxThan100:
      'Policy holder age cannot be larger than 100 years old.',
    policyDOBLessThan18: 'Policy holder age cannot be less than 18 years old.',
    selectPlaceholder: 'Please select',
    enterDOB: 'Enter DOB',
  },
  datePicker: {
    today: 'Today',
    yesterday: 'Yesterday',
    last7Days: 'Last 7 Days',
    last14Days: 'Last 14 Days',
    last30Days: 'Last 30 Days',
    lastMonth: 'Last month',
    lifeTime: 'Life time',
    thisWeek: 'This week',
    thisMonth: 'This month',
  },
  errorMessage: {
    dateInvalid: '',
    inputInvalid: 'Please input search data',
    selectInvalid: 'Please select dropdown list',
  },
  importData: {
    error: {
      required: '{{fieldName}} is required in row {{rowNumber}}.',
      transient: '{{message}} in row {{rowNumber}}.',
      invalidWField: '{{fieldName}} {{message}} in row {{rowNumber}}',
      invalidNoField: '{{message}} in row {{rowNumber}}',
      notExist:
        "Value provided for {{fieldName}} doesn't exist in {{rowNumber}}",
    },
  },
  leadDetailFields: {
    year: 'Year',
    brand: 'Brand',
    model: 'Model',
    sumInsured: 'Sum insured',
    engineSize: 'Engine size',
    engineNumber: 'Engine Number',
    transmission: 'Transmission',
    dashCam: 'Dash cam',
    purpose: 'Purpose',
    province: 'Province',
    modification: 'Modification',
    licensePlate: 'License plate',
    gender: 'Gender',
    dob: 'DOB',
    age: 'Age',
    city: 'City',
    leadType: 'Lead Type',
    leadId: 'Lead Id',
    reference: 'Reference',
    redPlate: 'Red plate',
    firstName: 'First Name',
    lastName: 'Last Name',
    'tax/companyTax': 'Tax/Company Tax',
    nationalId: 'National ID',
    company: 'Company',
    commLanguage: 'Comm. Language',
    title: 'Title',
    orderType: 'Order Type',
    customerId: 'Customer ID',
    renewalId: 'Renewal ID',
    orderId: 'Order ID',
    team: 'Team',
    supervisor: 'Supervisor',
    salesAgent: 'Sales Agent',
    drivingPurpose: 'Driving purpose',
    firstDriverName: '1st driver name',
    firstDriverDOB: '1st driver DOB',
    secondDriverName: '2nd driver name',
    secondDriverDOB: '2nd driver DOB',
    customerFirstName: 'Customer First Name',
    customerLastName: 'Customer Last Name',
    motorInsuranceTypeOne: 'Motor Insurance Type 1',
    motorInsuranceMandatory: 'Motor Insurance Mandatory',
    motorInsuranceMotorAddOn: 'Motor Insurance Motor Add-on',
    idCard: 'ID Card',
    firstNamedDriverLicense: 'First Named Driver License',
    secondNamedDriverLicense: 'Second Named Driver License',
    vehicleRegistration: 'Vehicle Registration',
    vehiclePictureFront: 'Vehicle Picture Front',
    vehiclePictureBack: 'Vehicle Picture Back',
    vehiclePictureRight: 'Vehicle Picture Right',
    vehiclePictureLeft: 'Vehicle Picture Left',
    dashCamPicture: 'Dash Cam Picture',
    others: 'Others',
    latestLead: 'Latest lead',
    latestOrder: 'Latest order',
    agentName: 'Agent Name',
    noOfDoor: 'No.of door',
    cabType: 'Cab type',
    voluntaryPolicyStartDate: 'Voluntary policy start date',
    compulsoryPolicyStartDate: 'Compulsory policy start date',
  },
  logoutOption: {
    selectStatus: 'Select Status',
    lunch: 'Lunch',
    coffee: 'Coffee',
    training: 'Training',
    meeting: 'Meeting',
    toilet: 'Toilet',
    dayend: 'Day End',
  },
  emailTemplateOption: {
    quote: {
      title: 'Rabbit Finance - car insurance quote {{leadId}}',
      content:
        'Thank you for choosing Rabbit Finance, Thailand’s largest online financial marketplace. We provide the best service and most competitive pricing in the market - guaranteed. \n\n[[url]] \n\nPlease see attached your car insurance quotation with detailed coverage information, order ID: {{leadId}} \n\nPlease reply to this email, if you would like to buy this package or if you have any questions. \n\nBest regards, \n\nRabbit Finance',
    },
    paymentFollowUp: {
      title: 'Rabbit Finance - order confirmation {{leadId}}',
      content:
        'Thank you for choosing Rabbit Finance. Thailand’s largest online financial marketplace. We provide the most competitive pricing in the market - guaranteed. \n\nPlease find attached your order confirmation and invoice. \n\nPackage: {{purchasePackage}} \n\nAs a next step, please complete the payment by choosing one of our payment options: \n\n[payment options] \n\nAfter your payment processed, we will provide you with a digital copy of the policy. And we will also send you the physical insurance policy soonest. \n\nBest regards, \n\nRabbit Finance',
    },
    notReachable: {
      title: 'Rabbit Finance - {{leadId}} Not reachable',
      content:
        'We could not reach you to discuss your car insurance inquiry. \n\nPlease reach me by calling 02-022-1222 or through LINE ID: @rabbitfinance \n\nWe appreciate your cooperation. \n\nBest regards, \n\nRabbit Finance',
    },
    renewalReminder: {
      title: '',
      content:
        'Hi Alex \n\nThanks for using our product. We’re really sad to see you go – but we had a good run. \n\nIf you have any outstanding questions, feel free to contact us at support@acme.com or +123456789. \n\nAnd, if you ever need a product like ours in future, we hope we’ll see you again. \n\nAll the best,',
    },
    noTemplate: {
      title: '',
      content: '',
    },
  },
  team: {
    admin: 'Admin',
    manager: 'Manager',
    sales: 'Sales',
    supervisor: 'Supervisor',
    inbound: 'Inbound Agent',
    customerService: 'Customer Service',
    documentsCollection: 'Documents Collection',
    qualityControl: 'Quality Control',
    submission: 'Submission',
  },
  weekDay: {
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
  },
  searchFieldLeadOption: {
    customerName: 'Customer Name',
    customerPhone: 'Customer Phone',
    customerEmail: 'Customer Email',
    id: 'ID',
  },
  dateTypeLeadOption: {
    createOn: 'Created on',
    updateOn: 'Updated on',
    assignOn: 'Assigned on',
    rejectOn: 'Rejected on',
    policyStartOn: 'Policy start date on',
    policyExpiryOn: 'Policy expiry date on',
  },
  dateType: {
    createdOn: 'Created on',
    updatedOn: 'Updated on',
  },
  leadTypeFilter: {
    new: 'New',
    retainer: 'Retainer',
    renewal: 'Renewal',
  },
  leadStatus: {
    new: 'New',
    valid: 'Valid',
    contacted: 'Contacted',
    interested: 'Interested',
    prospect: 'Prospect',
    purchased: 'Purchase',
    pendingPayment: 'Pending Payment',
    cancelled: 'Cancelled',
  },
  rejectReason: {
    wrongNumber: 'Wrong number: Not the owner of the car',
    cantContact: 'Phone number not working',
    noCar: 'Does not have a car',
    dontCall: 'Requested not to be called again',
    notExpiring: 'Not in 90 days policy expiry period',
    purchasedFromOther: 'Already purchase insurance from other insurer',
    purchasedFromRabbit: 'Already purchase insurance from Rabbit Finance',
  },
  statusCollection: {
    active: 'Active',
    inactive: 'Inactive',
  },
  insuranceTypes: {
    type1: 'Type 1',
    type2: 'Type 2',
    type2Plus: 'Type 2+',
    type3: 'Type 3',
    type3Plus: 'Type 3+',
    mandatory: 'Mandatory',
  },
  leadSourceTypes: {
    online: 'Online',
    offline: 'Offline',
  },
  autoAssignOption: {
    all: 'All',
    yes: 'Yes',
    no: 'No',
  },
  hideOption: {
    yes: 'Yes',
    no: 'No',
  },
  statusOptions: {
    active: 'Active',
    suspended: 'Suspended',
  },
  importFileStatus: {
    complete: 'Success',
    inProgress: 'In progress',
    error: 'Failed',
  },
  productionOptions: {
    carInsurance: 'Car Insurance',
  },
  api: {
    'roles/admin': 'Admin',
    'roles/manager': 'Manager',
    'roles/supervisor': 'Supervisor',
    'roles/sales': 'Sale Agent',
    'roles/inbound': 'Inbound Agent',
    'roles/customer-service': 'Customer Service',
    'roles/documents-collection': 'Documents Collection',
    'roles/quality-control': 'Quality Control',
    'roles/submission': 'Submission',
    'roles/problem-case': 'Problem Case',
  },
  qcStatus: {
    preApproved: 'Pre-Approved',
    criticalIssues: 'Critical Issues',
    issuesFixed: 'Issues Fixed',
  },
  statusOption: {
    preSubmitted: 'Pre-Submitted',
  },
  approveStatus: {
    endorsement: 'Endorsement',
    otherProblems: 'Other Problems',
  },
  menu: {
    lead: {
      root: 'Leads',
      assignment: 'Assignment',
      rejections: 'Rejections',
      all: 'All',
      import: 'Import',
      distribution: 'Distribution',
      sources: 'Sources',
      scoring: 'Scoring',
      overflow: 'Overflow',
      segmentation: 'Segmentation',
    },
    order: {
      root: 'Orders',
      all: 'All',
      documents: 'Documents',
      QC: 'QC',
      submission: 'Submission',
      approval: 'Approval',
    },
    userManagement: {
      root: 'User management',
      users: 'Users',
      teams: 'Teams',
    },
    package: {
      root: 'Package',
      search: 'Search',
      import: 'Import',
    },
    carDiscount: {
      root: 'Car Discount - Import',
    },
  },
  titleTag: {
    orderAll: 'All Orders | Order Management',
    orderDocument: 'Documents Module | Order Management',
    orderQC: 'QC Module | Order Management',
    orderSubmission: 'Submission Module | Order Management',
    orderApproval: 'Approval Module | Order Management',
  },
  orderUpdateFrm: {
    pending: 'Documents pending',
    missing: 'Start submission with missing documents',
    complete: 'Documents complete',
    submission: 'Cannot collect documents in time for submission',
    warning: 'Missing information:',
    commentLbl: 'Comment',
    commentPlaceholder: 'All documents received.',
  },
  customQuote: {
    packageTypes: {
      standard: 'Standard',
      renewal: 'Renewal',
      transfer: 'Transfer Code',
    },
  },
  shortInsurers: {
    1: 'Allianz C.P.',
    2: 'Thai Paiboon Insurance',
    3: 'Aioi Bangkok Insurance',
    4: 'Asia Insurance',
    5: 'Assets Insurance',
    6: 'AXA Insurance',
    7: 'Bangkok Insurance',
    8: 'Chao Phaya Insurance',
    9: 'Charan Insurance',
    10: 'Deves Insurance',
    11: 'Dhipaya Insurance',
    12: 'Erawan Insurance',
    13: 'Indara Insurance',
    14: 'Kamol Insurance',
    15: 'KSK Insurance',
    16: 'Mittare Insurance',
    17: 'Muang Thai Insurance',
    18: 'Nam Seng Insurance',
    19: 'Southeast Insurance',
    20: 'Syn Mun Kong Insurance',
    21: 'Thai Insurance',
    22: 'Siam City Insurance',
    23: 'Thai Setakij Insurance',
    24: 'Thaisri Insurance',
    25: 'Thaivivat Insurance',
    26: 'Tokio Marine Insurance',
    27: 'Viriyah Insurance',
    28: 'Thanachart Insurance',
    29: 'Samaggi Insurance',
    30: 'Generali Insurance',
    31: 'Navakij Insurance',
    32: 'Krungthai Panich Insurance',
    33: 'LMG Insurance',
    34: 'MSIG Insurance',
    35: 'Tokio Marine Safety Insurance',
    36: 'Sri Ayudhaya General Insurance',
    37: 'AIG Insurance',
    38: 'ROOJAI',
    40: 'CHUBB',
    42: 'FPG',
  },
  longInsurers: {
    1: 'Allianz  General Insurance Public Company Limited',
    2: 'Thai Paiboon Insurance PLC',
    3: 'Aioi Bangkok Insurance Public Company Limited',
    4: 'Asia Insurance 1950 Co., Ltd',
    5: 'Assets Insurance Public Company Limited',
    6: 'AXA Insurance Pubilic Company Limited',
    7: 'Bangkok Insurance Public Company Limited',
    8: 'Chao Phaya Inurance Pubilic Company Limited',
    9: 'Charan Insurance Public Company Limited',
    10: 'The Deves Insurance Public Company Limited',
    11: 'Dhipaya Insurance Public Company Limited',
    12: 'Erawan Insurance Co.,Ltd.',
    13: 'Indara Insurance Public Company Limited',
    14: 'Kamol Insurance Public Company Limited',
    15: 'KSK Insurance (Thailand) Public Company Limited',
    16: 'Mittare Insurance Public Company Limited',
    17: 'Muang Thai Insurance Public Company Limited',
    18: 'Nam Seng Insurance Public Company Limited',
    19: 'The South East Insurance Public Company Limited',
    20: 'Syn Mun Kong Insurance Public Company Limited',
    21: 'Thai Insurance Public Company Limited',
    22: 'Siam City Insurance PLC',
    23: 'Thai Setakij Insurance Public Company Limited',
    24: 'Thaisri Insurance Public Company Limited',
    25: 'Thaivivat Insurance Public Co., Ltd.',
    26: 'Tokio Marine Insurance (Thailand) Public Company Limited',
    27: 'The Viriyah Insurance Company Limited',
    28: 'Thanachart Insurance Co., Ltd',
    29: 'Samaggi Insurance Company Limited (Thailand)',
    30: 'Generali Insurance (Thailand) Public Company Limited',
    31: 'The Navakij Insurance Public Company Limited',
    32: 'Krungthai Panich Insurance Public Company Limited',
    33: 'LMG Insurance Company Limited',
    34: 'MSIG Insurance (Thailand) Public Company Limited',
    35: 'Tokio Marine Safety Insurance (Thailand) PCL',
    36: 'Sri Ayudhaya General Insurance Public Company Limited',
    37: 'AIG Insurance (Thailand) Public Company Limited',
    38: 'Roojai Insurance',
    40: 'Chubb Samaggi Insurance Co. (PLC)',
    42: 'FPG Insurance',
  },
  motoType: {
    type1: 'Type 1',
    type2: 'Type 2',
    type2Plus: 'Type 2+',
    type3: 'Type 3',
    type3Plus: 'Type 3+',
  },
};
