export default {
  text: {
    add: 'เพิ่ม',
    addLeadButton: 'เพิ่มลีด',
    addCouponSuccess: 'เพิ่มคูปองสำเร็จ',
    alertLeadId: 'ลีดของคุณที่มีรหัสลีด {{leadId}} ถูกสร้างแล้ว',
    addLead: 'เพิ่มลีด',
    autoAssign: 'มอบหมายอัตโนมัติ',
    agentLead: 'ตัวแทน/ลีด',
    agentScore: 'คะแนนตัวแทน',
    assign: 'มอบหมาย',
    assignedToUser: 'มอบหมายให้ผู้ใช้',
    assignedToTeam: 'มอบหมายให้ทีม',
    assignedOrderSuccess: 'Assigned order successfully',
    assignedOrderFailed: 'Assigned order failed',
    unassignedOrderSuccess: 'Unassigned order successfully',
    unassignedOrderFailed: 'Unassigned order failed',
    addAddressSuccessful: 'เพิ่มที่อยู่เรียบร้อยแล้ว',
    addPhoneTitle: 'เพิ่มหมายเลขโทรศัพท์ใหม่',
    addButton: 'เพิ่ม',
    address: 'ที่อยู่',
    addressUseMultiple: 'ที่อยู่ที่ใช้ (เลือกหลายรายการ)',
    addressType: 'ประเภทที่อยู่',
    appointment: 'ตารางนัดหมาย',
    appointmentBtn: 'ตารางนัดหมาย',
    appointmentDate: 'วันที่นัดหมาย',
    apply: 'นำไปใช้',
    addNewAddress: 'เพิ่มที่อยู่ใหม่',
    addNewEmailAddress: 'เพิ่มที่อยู่อีเมล์ใหม่',
    addUser: 'เพิ่มผู้ใช้งาน',
    addUserToTeamFail: 'สร้างผู้ใช้งานแล้ว แต่ไม่สามารถเพิ่มลงในทีมได้',
    activate: 'เปิดใช้งาน',
    activateUserSuccess: 'การเปิดใช้งานผู้ใช้งานสำเร็จ',
    activateUserFailed: 'การเปิดใช้งานผู้ใช้งานไม่สำเร็จ',
    agent: 'ตัวแทน',
    addEmailSuccess: 'เพิ่มอีเมลเรียบร้อยแล้ว',
    addPhoneSuccess: 'เพิ่มหมายเลขโทรศัพท์เรียบร้อยแล้ว',
    age: 'อายุ',
    agentName: 'ชื่อตัวแทน',
    addLeadSuccess: 'สร้างลีดสำเร็จ',
    addCoupon: 'เพิ่มคูปอง',
    assignOn: 'มอบหมายเมื่อ',
    appointmentType: 'ประเภทการนัดหมาย',
    billing: 'การเรียกเก็บเงิน',
    bulkImportantSuccess: 'เพิ่มเครื่องหมายว่าสำคัญที่ลีดของคุณสำเร็จแล้ว',
    bulkUnimportantSuccess: 'นำเครื่องหมายว่าสำคัญออกจากลีดของคุณสำเร็จแล้ว',
    cancelButton: 'ยกเลิก',
    confirmImport: 'ยืนยันการนำเข้า',
    confirmButton: 'ยืนยัน',
    createTeam: 'สร้างทีม',
    closeButton: 'ปิด',
    createBy: 'สร้างโดย',
    createOn: 'สร้างเมื่อ',
    createUser: 'สร้างผู้ใช้งาน',
    clearAll: 'ลบทั้งหมด',
    createSource: 'สร้างแหล่งที่มา',
    companyName: 'ชื่อบริษัท',
    company: 'บริษัท',
    carBrand: 'ยี่ห้อรถ',
    carDashcam: 'กล้องติดรถยนต์',
    carEngineSize: 'ขนาดเครื่องยนต์ของรถ',
    carModel: 'รุ่นรถ',
    carModification: 'การปรับแต่งรถ',
    carRegisteredProvince: 'จังหวัดที่จดทะเบียนรถ',
    carYear: 'ปีรถ',
    carTransmission: 'ระบบเกียร์รถ',
    carUsage: 'การใช้รถ',
    createAdminTeam: 'สร้างทีมแอดมิน',
    create: 'สร้าง',
    createTeamSuccess: 'สร้างทีมสำเร็จ',
    createTeamFail: 'สร้างทีมไม่สำเร็จ',
    createUserSuccessfully: 'สร้างผู้ใช้งานสำเร็จแล้ว',
    createUserFail: 'เกิดข้อผิดพลาดในการสร้างผู้ใช้งาน: {{message}}',
    createOrderSuccess: 'สร้างออเดอร์สำเร็จ',
    creteOrderFail: 'สร้างออเดอร์ไม่สำเร็จ',
    callErrorMessage: 'ไม่มีการโทรสำหรับลีดนี้',
    callInProgressMessage: 'กำลังดำเนินการโทร',
    createNewCustomer: 'สร้างเป็นลูกค้าใหม่',
    confirmCustomer: 'ยืนยันลูกค้า',
    cantConfirmNow: 'ยังไม่สามารถยืนยันได้',
    confirmToCreateCustomer: 'ยืนยันการสร้างโปรไฟล์ลูกค้าใหม่',
    connectLeadToCustomer: 'เชื่อมโยงหลีดนี้กับพบโปรไฟล์ลูกค้าที่พบในระบบ',
    changeStatus: 'เปลี่ยนสถานะ',
    updateUserSuccessfully: 'อัปเดตผู้ใช้งานเรียบร้อยแล้ว',
    updateUserFail: 'เกิดข้อผิดพลาดในการอัปเดตผู้ใช้งาน: {{message}}',
    updateTeamSuccessfully: 'อัปเดตทีมเรียบร้อยแล้ว',
    updateTeamFail: 'อัปเดตทีมไม่สำเร็จ',
    createLeadSourceSuccessfully: 'สร้างแหล่งที่มาของลีดสำเร็จแล้ว',
    createLeadSourceFail:
      'เกิดข้อผิดพลาดในการสร้างแหล่งที่มาของลีด: {{message}}',
    createLeadSourceScoreFail:
      'สร้างแหล่งที่มาแล้วแต่เกิดข้อผิดพลาดในการบันทึกคะแนน โปรดแก้ไข และลองอีกครั้ง',
    createRejectionSuccessfully: 'การปฏิเสธลีดสำเร็จแล้ว',
    updateRejectionSuccessfully: 'เปลี่ยนสถานะลีดสำเร็จแล้ว',
    createRejectionFail: 'เกิดข้อผิดพลาดในการปฏิเสธลีด: {{message}}',
    currentInsurer: 'บริษัทประกันปัจจุบัน',
    connectedCall: 'การโทรถูกเชื่อมต่อแล้ว',
    connectDials: 'การโทรที่เชื่อมต่อ',
    cc: 'ส่งสำเนาถึง',
    content: 'เนื้อหา',
    comment: 'แสดงความคิดเห็น',
    call: 'โทร',
    campaign: 'แคมเปญ',
    createAppointmentSuccess: 'สร้างการนัดหมายสำเร็จ',
    createdOn: 'สร้างขึ้นเมื่อ',
    communicationType: 'ประเภทการสื่อสาร',
    copiedRecoveryLinkToClipboard:
      'คัดลอกลิงก์ที่กู้ไปยังคลิปบอร์ดแล้ว ลิงค์นี้สามารถใช้ได้เพียงครั้งเดียว และสามารถส่งได้ผ่านอีเมลเท่านั้น',
    coupon: 'คูปอง',
    couponCode: 'รหัสคูปอง',
    couponDiscount: 'คูปองส่วนลด',
    couponValidateMessage: 'ลีดอยู่ในสถานะซื้อ',
    customer: 'ลูกค้า',
    customerId: 'รหัสลูกค้า',
    customerAgreed: 'ลูกค้ายอมรับเวลาที่ตัวแทนเสนอ',
    customerRequested: 'ลูกค้าเป็นผู้นัดหมายเวลา',
    customerProfile: 'โปรไฟล์ลูกค้า',
    dragDropFileOrChooseFile: 'ลากและวางไฟล์ที่นี่ หรือ เลือกไฟล์',
    dropFilesHere: 'วางไฟล์ที่นี่',
    district: 'อำเภอ',
    date: 'วันที่',
    datePresets: 'วันที่ที่ตั้งไว้ล่วงหน้า',
    dailyLimit: 'ขีดจำกัดลีดรายวัน',
    dob: 'วันเกิด',
    unassign: 'ยกเลิกการมอบหมาย',
    unassigned: 'ยังไม่ได้มอบหมาย',
    unDeleteUserSuccessfully: 'ยกเลิกการลบผู้ใช้งานเรียบร้อยแล้ว',
    unDeleteUserFailed: 'ยกเลิกการลบผู้ใช้งานล้มเหลว',
    createLeadFail: 'การสร้างลีดล้มเหลว',
    dataIsUnavailable: 'ไม่มีข้อมูล',
    deleteCouponModal: 'คุณต้องการลบรหัสคูปองหรือไม่?',
    deleteCouponSuccess: 'ลบคูปองสำเร็จ',
    doYouWantTo: 'Do you want to',
    orderAssign: 'order',
    ordersAssign: 'orders',
    leadAssign: 'lead',
    leadsAssign: 'leads',
    editTeam: 'แก้ไขทีม',
    enable: 'เปิดใช้งาน',
    editUser: 'แก้ไขผู้ใช้งาน',
    email: 'อีเมล์',
    emptyFile: 'ไฟล์ว่างเปล่า',
    editAdminTeam: 'แก้ไขทีมแอดมิน',
    entries: 'รายการ',
    editNewLeadSuccess: 'อัปเดตลีดเรียบร้อยแล้ว',
    editRetainerLeadSuccess: 'อัปเดตลีดเรียบร้อยแล้ว',
    editNewLeadFail: 'เกิดข้อผิดพลาดในการอัปเดตลีด: {{message}}',
    editRetainerLeadFail: 'เกิดข้อผิดพลาดในการอัปเดตลีด: {{message}}',
    errorGettingRecoveryLink:
      'เกิดข้อผิดพลาดในการสร้างลิงก์สำหรับกู้คืนรหัสผ่าน',
    expiryDate: 'วันหมดอายุ',
    emailTemplate: 'เทมเพลตอีเมล',
    emailMessageUpdatedSuccess: 'อัปเดตข้อความอีเมลเรียบร้อยแล้ว',
    enterSubject: 'ใส่หัวข้อ',
    enterMessage: 'ใส่ข้อความ',
    enterCC: 'ใส่สำเนาถึง',
    enterFullName: 'ใส่ชื่อ - นามสกุล',
    enterFirstName: 'ใส่ชื่อจริง',
    enterLastName: 'ใส่นามสกุล',
    enterAddress: 'ใส่ที่อยู่',
    enterCompanyName: 'ใส่ชื่อบริษัท',
    enterTaxId: 'ใส่หมายเลขประจำตัวผู้เสียภาษี',
    enterPhoneNumber: 'ใส่เบอร์โทรศัพท์',
    enterPaymentAmount: 'ใส่จำนวนเงินที่ชำระ',
    enterPaymentDate: 'ใส่วันที่ชำระ',
    enterAppointmentDate: 'วว/ดด/ปปปป',
    enterEmail: 'ใส่ที่อยู่อีเมล',
    enterCoupon: 'ใส่หมายเลขคูปอง',
    errorMessage: 'Error: {{message}}',
    existingInformation: 'ข้อมูลเดิม',
    failedDials: 'ต่อสายไม่สำเร็จ',
    female: 'Female',
    fieldMismatch: 'Field mismatch',
    fileName: 'ชื่อไฟล์:',
    firstName: 'ชื่อจริง',
    firstNameAsterisk: 'ชื่อจริง *',
    fullName: 'ชื่อเต็ม',
    first: 'เริ่มต้น',
    free: 'ที่ว่าง',
    fileSizeLimit:
      'ไฟล์ {{fileName}} ถูกปฏิเสธ ไฟล์ใหญ่เกินไป จำกัดขนาด 1 เมกะไบต์',
    from: 'จาก',
    followup: 'Followup',
    forward: 'ส่งต่อ',
    gender: 'เพศ',
    gitVersion: 'เวอร์ชั่น',
    gitVersionUnknown: '<ไม่ปรากฏ>',
    goToHomePage: 'ไปที่หน้าแรก',
    hide: 'ซ่อน',
    hangUp: 'วางสาย',
    instruction1: '1. ความยาวอย่างน้อย 8 ตัวอักษร',
    instruction2: '2. ประกอบไปด้วยตัวอักษรพิมพ์เล็ก และพิมพ์ใหญ่',
    instruction3: '3. ประกอบไปด้วยตัวอักษร (a-z), (A-Z) และตัวเลข (0-9)',
    instruction4:
      '4. ประกอบไปด้วยเครื่องหมาย หรืออักขระพิเศษอย่างน้อย 1 ตัว เช่น ! @ # ? ] ! $ % ^ & * ( ) / \\  ',
    importCarDiscountFile: 'นำเข้าไฟล์ส่วนลด',
    importCarDiscountFileInProgress: 'กำลังดำเนินการนำเข้าไฟล์ส่วนลด',
    importCSVSuccess: 'นำเข้า CSV สำเร็จ',
    importCSVFailed: 'นำเข้าไม่สำเร็จ',
    importPackages: 'นำเข้าแพคเกจ',
    importPackagesProgress: 'กำลังดำเนินการนำเข้าแพคเกจ',
    importRenewPackages: 'เพิ่มแพคเกจต่ออายุ',
    importLead: 'นำเข้าลีด',
    importStatus: 'สถานะการนำเข้า',
    importDate: 'วันที่นำเข้า',
    importedBy: 'นำเข้าโดย',
    importedOn: 'นำเข้าเมื่อ',
    importedUser: 'นำเข้าผู้ใช้งาน',
    importFile: 'นำเข้าไฟล์',
    insurer: 'บริษัทประกัน',
    installment: '{{installmentNumber}} ครั้ง',
    installments: '{{installmentNumber}} งวดการผ่อนชำระ',
    invalidCoupon: 'รหัสคูปองไม่ถูกต้อง',
    invalidDataFormat:
      'โปรดใส่ข้อมูลที่ถูกต้องสำหรับ {{column}} ของแถว {{row}}',
    invalidEmail: '{{email}} ไม่ใช่ที่อยู่อีเมลที่ถูกต้อง',
    invalidEmail2: 'อีเมลไม่ถูกต้อง',
    invalidRabbitEmail: '{{email}} ไม่ใช่ที่อยู่อีเมลแรบบิท',
    isExistedEmail: '{{email}} เคยถูกเพิ่มไปแล้ว',
    input: 'นำเข้า',
    inputName: 'ใส่ชื่อ',
    inputUser: 'เลือกผู้ใช้งาน',
    importUserFail: 'นำเข้าผู้ใช้ล้มเหลว',
    invalidDateSearch: 'โปรดเลือกวันนี้หรือวันถัดไป!',
    invalidSundaySearch: 'ไม่อนุญาตให้นัดหมายในวันอาทิตย์!',
    invalidDateWithCurrent:
      'วันที่ต้องเป็นวันหลังจากวันเริ่มต้นความคุ้มครอง “current date”',
    invalidDateFromCurrent:
      'วันที่ต้องเป็นวันก่อนวันเริ่มต้นความคุ้มครอง ““current date + {{month}} months”',
    inputFirstNameValid: 'โปรดระบุชื่อจริงที่ถูกต้อง',
    inputLastNameValid: 'โปรดระบุนามสกุลที่ถูกต้อง',
    inputMaxLength: 'ต้องยาวไม่เกิน {{length}} ตัวอักษร',
    inputInvalid: 'ข้อมูลในช่องไม่ถูกต้อง',
    kb: 'กิโลไบต์',
    lastVisitedOn: 'เข้าชมล่าสุดเมื่อวันที่',
    leadSetting: 'การตั้งค่าลีด',
    loginSuccess: 'เข้าสู่ระบบสำเร็จ',
    loginFailed: 'เข้าสู่ระบบล้มเหลว!',
    logout: 'ออกจากระบบ',
    leadCount: 'จำนวนลีด',
    leadFound: 'เราพบ {{count}} ลีด',
    leadFound_plural: 'เราพบ {{count}} ลีด',
    lastLoginOn: 'เข้าสู่ระบบครั้งสุดท้ายเมื่อ',
    lastName: 'นามสกุล',
    lastNameAsterisk: 'นามสกุล *',
    lastInsurer: 'ผู้รับประกันภัยล่าสุด',
    lastPremium: 'เบี้ยประกันล่าสุด',
    leadAge: 'อายุลีด',
    leadSource: 'ที่มาของลีด',
    leadSourceAsterisk: 'ที่มาของลีด*',
    leadType: 'ประเภทลีด',
    leadPriority: 'ลีด/ลำดับความสำคัญ',
    lead: 'ลีด {{number}}',
    leadId: 'รหัสลีด',
    leadRecord: 'บันทึกลีด',
    leadStatus: 'สถานะลีด',
    leadScore: 'คะแนนลีด',
    logoutSuccess: 'ผู้ใช้งานออกจากระบบสำเร็จ',
    logoutFailed: 'ผู้ใช้งานออกจากระบบไม่สำเร็จ: {{message}}',
    loading: 'กำลังโหลด ...',
    lifeTime: 'ระยะเวลาในการใช้งาน',
    licensePlate: 'ทะเบียนรถ',
    leadInformation: 'ข้อมูลลีด',
    latestInformation: 'ข้อมูลล่าสุด',
    mandatory: 'ภาคบังคับ',
    manager: 'ผู้จัดการ',
    missingHeaderFile: 'ไฟล์ไม่สมบูรณ์ หัวข้อหายไป',
    min: 'ต่ำสุด',
    message: 'ข้อความ',
    male: 'Male',
    markImportant: 'ทำเครื่องหมายว่าสำคัญ',
    markUnimportant: 'ทำเครื่องหมายว่าไม่สำคัญ',
    medium: 'ปานกลาง',
    minimum: 'ขั้นต่ำ',
    maximum: 'ขั้นสูง',
    maximumUpload: 'อัปโหลดสูงสุดสำหรับ {{type}} เท่ากับ {{maxNumber}}',
    marketingConsent: 'ความยินยอมด้านการตลาด',
    mailboxCommunications: 'กล่องจดหมาย',
    miss: 'Miss',
    mr: 'Mr',
    mrs: 'Mrs',
    myBestGuess: 'ตัวแทนคาดคะเนเวลาสำหรับการติดต่อ',
    nationalIdPassport: 'National ID / passport',
    new: 'ใหม่',
    newLead: 'ลีดใหม่',
    newLeads: 'ลีดใหม่',
    no: 'ไม่',
    numberOfPackages: 'เลขที่ แพคเกจ',
    noDots: 'เลขที่',
    name: 'ชื่อ',
    newMessage: 'ข้อความใหม่',
    noData: 'ไม่มีข้อมูล',
    networkError: 'Network error',
    netPremium: 'Net Premium',
    orderStatus: 'Order Status',
    overFlowError:
      'คุณไม่สามารถบันทึกได้หากตัวเลือกสองตัวเลือก หรือมากกว่านั้นมีเลขซ้ำกัน',
    other: 'อื่นๆ',
    paymentType: 'Payment type',
    paymentTerms: 'Payment terms',
    passedBookingTime: 'หมดเวลาจอง!',
    passwordError:
      'รหัสผ่านของคุณอยู่ในรูปแบบที่ไม่ถูกต้อง โปรดตั้งรหัสผ่านของคุณตามรูปแบบที่ให้ไว้ด้านล่าง',
    preferredInsurer: 'บริษัทประกันที่ต้องการ',
    preferredType: 'ประเภทประกันภาคสมัครใจที่ต้องการ',
    premiumBeforeDiscount: 'เบี้ยก่อนหักส่วนลด',
    phone: 'หมายเลขโทรศัพท์',
    phoneAsterisk: 'หมายเลขโทรศัพท์ *',
    product: 'ผลิตภัณฑ์',
    phoneNumber: 'หมายเลขโทรศัพท์',
    packageType: 'ชนิดของแพคเกจ',
    paymentCall: 'รอการชำระเงิน',
    priceAfterDiscount: 'ราคาหลังหักส่วนลด',
    priority: 'ลำดับความสำคัญ {{role}}',
    province: 'จังหวัด',
    postcode: 'รหัสไปรษณีย์',
    policy: 'กรมธรรม์',
    policyholder: 'Policyholder',
    policyId: 'Policy ID',
    policies: 'Policies',
    policyStartDate: 'วันเริ่มความคุ้มครอง',
    policyStartingDate: 'วันที่เริ่มกรมธรรม์',
    policyPreferredType: 'ประเภทกรมธรรม์ที่ต้องการ',
    personal: 'ส่วนบุคคล',
    placeHolderCc: 'พิมพ์ หรือ วาง ที่อยู่อีเมลแรบบิท และ กด "Enter หรือ Tab" ',
    pushCommentSuccess: 'ส่งความคิดเห็นสำเร็จ',
    leftComment: '{{name}} แสดงความคิดเห็น',
    systemUser: 'ระบบ',
    paymentConfirmation: 'ยืนยันการชำระเงิน',
    paymentAmount: 'จำนวนเงินที่ชำระ (บาท)',
    paymentDate: 'วันที่ชำระ',
    paymentSchedule: 'กำหนดการชำระเงิน',
    pleaseSelect: 'โปรดเลือก',
    permissionDenied: 'คุณไม่มีสิทธิ์เข้าถึงส่วนนี้',
    paymentAmountRequired: 'จำเป็นต้องระบุจำนวนเงิน!',
    paymentDateRequired: 'จำเป็นต้องระบุวันที่ชำระเงิน!',
    packageNotFound: 'ไม่พบแพคเกจ!',
    policyHolderInformation: 'ผู้ถือกรมธรรม์',
    pleaseChooseCorrectCustomer: 'โปรดเลือกข้อมูลลูกค้าที่ถูกต้อง',
    inputSumInsuredError:
      'กรุณาใส่ทุนประกันสูงสุด {{label}} มากกว่าทุนประกันต่ำสุด {{label}}',
    quoteFollowUp: 'ติดตามผลการเสนอราคา',
    quotesAndPackageURL: 'ลิงก์ใบเสนอราคา & แพคเกจ',
    requiredMinMax: 'โปรดใส่ทั้งค่าสูงสุด และค่าต่ำสุด {{label}}',
    requiredCsvValidation: 'เฉพาะไฟล์ CSV',
    requiredColumnValidation: 'คอลัมน์ {{column}} หายไป',
    requiredRowsValidation: '{{name}} แถว {{row}} ขาด {{column}}',
    requiredFirstName: 'จำเป็นต้องใส่ชื่อ',
    requiredLastName: 'จำเป็นต้องใส่นามสกุล',
    requiredPhone: 'จำเป็นต้องใส่เบอร์โทรศัพท์',
    required: 'จำเป็น',
    retainer: 'รีเทนเนอร์',
    retainerLead: 'รีเทนเนอร์ลีด',
    retainerLeads: 'รีเทนเนอร์ลีด',
    renewal: 'ต่ออายุ',
    renewalLead: 'ลีดต่ออายุ',
    renewalId: 'รหัสลีดต่ออายุ',
    referenceId: 'รหัสอ้างอิง',
    requestCustomQuote: 'สร้างใบเสนอราคาเอง',
    addPayslip: 'เพิ่มหลักฐานการชำระเงิน',
    recoveryLink: 'ลิงค์กู้คืนรหัสผ่าน',
    rejectLead: 'ปฏิเสธ',
    rejectionReason: 'เหตุผลในการปฏิเสธ',
    replyAll: 'ตอบกลับทั้งหมด',
    reply: 'ตอบกลับ',
    replyMessage: 'ข้อความตอบกลับ',
    search: 'ค้นหา',
    selectFiles: 'ลาก หรือคลิกเพื่อเลือกไฟล์',
    searchResults: 'ผลการค้นหา: {{results}} รายการ',
    settings: 'การตั้งค่า',
    selectAppointmentTypes: 'เลือกประเภทการนัดหมาย',
    selectUsers: 'เลือกผู้ใช้งาน',
    supervisor: 'ซุปเปอร์ไวเซอร์',
    scoringError: 'ผลรวมควรเท่ากับ 100',
    sequence: 'ลำดับ',
    source: 'ที่มา',
    score: 'คะแนน',
    status: 'สถานะ',
    suspend: 'ระงับ',
    saveButton: 'บันทึก',
    selectDateType: 'ประเภทวันที่',
    shipment: 'การจัดส่ง',
    show: 'แสดง',
    subTotal: 'Subtotal',
    suspendUserSuccess: 'ระงับผู้ใช้งานสำเร็จ',
    suspendUserFailed: 'ระงับผู้ใช้งานไม่สำเร็จ',
    sumInsured: 'ทุนประกันที่ต้องการ',
    startDate: 'วันที่เริ่มต้น',
    youngestDriverDob: 'วันเกิดของผู้ขับขี่ที่อายุน้อยที่สุด',
    select: 'เลือก',
    save: 'บันทึก',
    send: 'ส่ง',
    sms: 'ข้อความ',
    subject: 'หัวข้อเรื่อง',
    subjectAsterisk: 'หัวข้อเรื่อง *',
    sum: 'รวม',
    summary: 'สรุป',
    sec: 'วินาที',
    signIn: 'เข้าสู่ระบบ',
    sumInsuredLabel: 'ทุนประกัน',
    sendEmailSuccess: 'ส่งอีเมลสำเร็จ',
    sendSmsSuccess: 'ส่งข้อความสำเร็จ',
    subDistrict: 'ตำบล',
    suspendAccount: 'บัญชีผู้ใช้ถูกระงับการใช้งาน',
    templateButton: 'เทมเพลต',
    today: 'วันนี้',
    totalCall: 'จำนวนครั้งในการโทรทั้งหมด',
    totalCallDuration: 'ระยะเวลาการโทรทั้งหมด',
    totalNetPremium: 'Total net premium',
    teamName: 'ชื่อทีม',
    team: 'ทีม ',
    teamRole: 'ตำแหน่งผู้ใช้งาน',
    template: 'เทมเพลต',
    total: 'รวม',
    totalDials: 'รวมที่ต่อสายทั้งหมด',
    taxId: 'เลขประจำตัวผู้เสียภาษี',
    totalLeadLimit: 'ขีดจำกัดลีดทั้งหมด',
    to: 'ถึง',
    totalMaxFileSize:
      '{{fileName}} ไม่สามารถเพิ่มได้ จำกัดขนาดสูงสุด 5 เมกะไบต์',
    transferCall: 'โอนสาย',
    transferCallComplete: 'โอนสายสำเร็จ',
    transfer: 'โอน',
    type: 'ประเภท',
    updateLeadButton: 'อัปเดตลีด',
    updateOn: 'อัปเดตเมื่อ',
    userRole: 'ตำแหน่งผู้ใช้งาน',
    updateUser: 'อัปเดตผู้ใช้งาน',
    updateSource: 'แหล่งอัปเดต',
    updateTeam: 'อัปเดตทีม',
    userFound: '{{count}} {{user}} ที่จะอัปเดต',
    user: 'ผู้ใช้งาน',
    userCount: 'จำนวนผู้ใช้งาน',
    userName: 'ชื่อผู้ใช้งาน',
    update: 'อัปเดต',
    unnecessaryRowsValidation:
      '{{name}} แถว {{row}} มีฟิลด์ที่ไม่จำเป็น {{column}}',
    unverified: 'ไม่ได้รับการตรวจสอบ',
    urgent: 'Urgent',
    urgentCall: 'Urgent call',
    updateNewLeadSuccess: 'อัปเดตลีดใหม่สำเร็จแล้ว',
    updateRetainerLeadSuccess: 'อัปเดตรีเทนเนอร์ลีดสำเร็จแล้ว',
    updateNewLeadFailed: 'เกิดข้อผิดพลาดในการอัปเดตลีดใหม่: {{message}}',
    updateRetainerLeadFailed:
      'เกิดข้อผิดพลาดในการอัปเดตรีเทนเนอร์ลีด: {{message}}',
    updateLeadSourceSuccessfully: 'อัปเดตแหล่งที่มาของลีดสำเร็จ',
    updateLeadSourceFail:
      'เกิดข้อผิดพลาดในการอัปเดตแหล่งที่มาของลีด: {{message}}',
    unsupportedFile: 'ไฟล์ {{fileName}} ถูกปฏิเสธ ไม่รองรับประเภทไฟล์',
    updateLeadSourceScoreFail: 'เกิดข้อผิดพลาดในการบันทึกที่มาคะแนน',
    updateLeadScoreSuccess: 'อัพเดต {{leadType}} คะแนนลีดสำเร็จ',
    updateLeadScoreFailed: 'อัพเดต {{leadType}} คะแนนลีดไม่สำเร็จ: {{message}}',
    utmMedium: 'สื่อการโฆษณา',
    utmCampaign: 'แคมเปญสื่อการโฆษณา',
    updateBy: 'อัปเดตโดย',
    updatedOn: 'อัปเดตเมื่อ',
    uploadAttachmentFail: 'อัปโหลดไฟล์แนบล้มเหลว',
    updateLeadSuccess: 'อัปเดตลีดเรียบร้อยแล้ว',
    updateLeadFail: 'อัปเดตโอกาสในการขายล้มเหลว',
    valid: 'สมบูรณ์',
    verified: 'ตรวจสอบแล้ว',
    landline: 'โทรศัพท์บ้าน',
    viewQuotes: 'ดูใบเสนอราคา',
    validatePhone: 'หมายเลขโทรศัพท์ควรเป็น 10 หลักและขึ้นต้นด้วย 0',
    viewRenewal: 'ดูใบต่ออายุ',
    voiceFile: 'ไฟล์เสียง',
    voucherDiscount: 'Voucher & discounts',
    website: 'Website',
    wrongDocument: 'Wrong Document',
    callDuration: 'ระยะเวลาการโทร',
    compose: 'เขียน',
    noMessageSelected: 'ไม่ได้เลือกข้อความ',
    yes: 'ใช่',
    viewPurchase: 'ดูการซื้อ',
    rowExcelInvalid: 'แถว {{row}} {{name}} "{{value}}" ไม่ถูกต้อง',
    webActivity: 'กิจกรรมบนเว็บ',
    remark: 'หมายเหตุ',
    minutes: 'นาที',
    minutesAcronym: 'ต่ำสุด',
    vehiclePolicy: 'รถยนต์ & กรมธรรม์',
    typeOfVehicle: 'ประเภทรถยนต์',
    chassisNumber: 'หมายเลขตัวถัง',
    searchImportFileName: 'ค้นหาด้วยชื่อไฟล์ที่นำเข้า',
    datePickerPlaceholder: 'วว/ดด/ปปปป - วว/ดด/ปปปป',
    general: 'ทั่วไป',
    approved: 'Approved',
    rejected: 'Rejected',
    pending: 'Pending',
    submitted: 'Submitted',
    deleteDocumentSuccessfully: 'Delete order document successfully.',
    updateOrderSuccessfully: 'Update order successfully',
    updateOrderFailed: 'Error: {{message}}',
    selectAll: 'Select All',
    item: '{{ count }} item',
    items: '{{ count }} items',
  },
  lead: {
    car: 'รถยนต์',
    changeCar: 'เปลี่ยนรถ',
    activity: 'กิจกรรม',
    communication: 'การสื่อสาร',
    assignment: 'การมอบหมายงาน',
    audit: 'การตรวจสอบ',
    remark: 'หมายเหตุ',
    comment: 'แสดงความคิดเห็น',
    allActivity: 'กิจกรรมทั้งหมด',
    document: 'เอกสาร',
  },
  order: {
    sale: 'Sales Info',
    customer: 'ข้อมูลลูกค้า',
  },
  compound: {
    taxId: 'เลขประจำตัวผู้เสียภาษี',
  },
  errors: {
    required: '{{field}} จำเป็นต้องระบุ',
    errorReasons: 'ข้อผิดพลาดเนื่องจาก:',
    invalidLicense: 'โปรดระบุทะเบียนรถยนต์ในรูปแบบที่ถูกต้อง',
  },
  errorPage: {
    notFoundText: 'ขออภัยสินค้าที่คุณกำลังมองหาไม่ได้อยู่บนเว็บไซต์อีกต่อไป',
    backToHomePage: 'ไปที่หน้าแรก >>',
  },
  appointmentType: {
    requested: 'Requested',
    agreed: 'Agreed',
    assumed: 'Assumed',
    document_follow_up: 'Document follow up',
    wrong_document: 'Wrong document',
  },
  timeSlotCallBack: {
    appointment: 'ตารางนัดหมาย',
    appointmentType: 'ประเภทการนัดหมาย',
    subject: 'หัวข้อเรื่อง',
    customerName: 'ชื่อลูกค้า',
    leadID: 'รหัสลีด',
    orderID: 'Order ID',
    viewMoreButton: 'ดูเพิ่มเติม',
  },
  package: {
    importFileName: 'ชื่อไฟล์',
    requiredFields: 'จำเป็น',
    minDate: 'วันที่เริ่มต้นต้องไม่อยู่ก่อนหน้าวันที่วันนี้',
    invalidDateFormat: 'รูปแบบวันที่ไม่ถูกต้อง',
    expirationDateAndStartDate: 'วันหมดอายุต้องไม่อยู่ก่อนหน้าวันที่เริ่มต้น',
    createPackageSuccessfully: 'สร้างแพคเกจสำเร็จ',
    saveAndSendPackageButton: 'บันทึกและส่งแพคเกจ',
    backButton: 'กลับ',
    packageTitle: 'แพคเกจ',
    carAndSumInsuredTitle: 'รถยนต์ และ ทุนประกัน',
    coverageTitle: 'ความคุ้มครอง',
    name: 'ชื่อแพคเกจ*',
    start_date: 'วันเริ่มแพคเกจ*',
    expiration_date: 'วันหมดอายุแพคเกจ*',
    insurance_company_id: 'บริษัทประกันภัย*',
    car_insurance_type: 'ประเภทประกันภัย*',
    oic_code: 'รหัส OIC*',
    car_repair_type: 'ประเภทการซ่อม*',
    modified_car_accepted: 'คุ้มครองอุปกรณ์ตกแต่งรถยนต์เพิ่มเติม?*',
    has_cctv_discount: 'รวมส่วนลดกล้อง?*',
    car_age: 'อายุรถยนต์(ปี)*',
    carAndSumInsured: 'ทุนประกัน*',
    sum_coverage_min: 'ต่ำสุด',
    sum_coverage_max: 'ทุนประกัน*',
    deductible_amount: 'ความเสียหายส่วนแรก(บาท)*',
    price: 'เบี้ยไม่รวม พ.ร.บ.(บาท)*',
    fire_theft_coverage: 'คุ้มครองสูญหายและไฟไหม้*',
    fire_theft_coverage_value: 'มูลค่า',
    flood_coverage: 'คุ้มครองน้ำท่วม*',
    flood_coverage_value: 'มูลค่า',
    car_submodels: 'รุ่นย่อยรถยนต์*',
    liability_per_person_coverage:
      'ความเสียหายต่อชีวิต ร่างกาย หรืออนามัยต่อคน(บาท)*',
    liability_per_accident_coverage:
      'ความเสียหายต่อชีวิต ร่างกาย หรืออนามัยต่อครั้ง(บาท)*',
    liability_property_coverage: 'ประกันความเสียหายต่อทรัพย์สิน(บาท)*',
    personal_accident_coverage: 'ประกันอุบัติเหตุส่วนบุคคล(บาท)*',
    personal_accident_coverage_no: 'จำนวนผู้เอาประกัน (PA)*',
    medical_expenses_coverage: 'ประกันค่ารักษาพยาบาล(บาท)*',
    medical_expenses_coverage_no: 'จำนวนผู้เอาประกัน (ME)*',
    bail_bond_coverage: 'ประกันผู้ขับขี่ (บาท)*',
    yes: 'ใช่',
    no: 'ไม่',
    garage: 'ซ่อมอู่',
    dealer: 'ซ่อมห้าง',
    stepValidation: 'ต้องคูณ 10,000',
    statusSearchLabel: 'สถานะ',
    insurerSearchLabel: 'บริษัทประกัน',
    priceSearchLabel: 'ราคา',
    carBrandSearchLabel: 'ยี่ห้อรถ',
    carModelSearchLabel: 'รุ่นรถ',
    subModelSearchLabel: 'รุ่นย่อย',
    carAgeSearchLabel: 'อายุรถ',
    provinceSearchLabel: 'จังหวัด',
    insuranceTypeSearchLabel: 'ประเภทประกันภัย',
    searchLabel: 'ค้นหา',
    downloadPackageAllBtn: ' ดาวน์โหลดแพคเกจทั้งหมด',
    carAgeMinMessage: 'ค่าไม่สามารถเป็น 0',
    packages: 'Packages',
    limitTimeSearchPackage: 'Search time greater than 3 minutes',
    package_type: 'ชนิดของแพคเกจ*',
    fixedDriver: 'จำนวนผู้ขับขี่',
    firstDriverDOB: 'ผู้ขับขี่คนที่ 1',
    secondDriverDOB: 'ผู้ขับขี่คนที่ 2',
    policyDOBMaxThan100: 'อายุต้องไม่มากกว่า 100 ปี',
    policyDOBLessThan18: 'อายุต้องไม่ต่ำกว่า 18 ปี',
    selectPlaceholder: 'ระบุข้อมูล',
    enterDOB: 'ใส่วันเกิดของผู้ขับขี่',
  },
  datePicker: {
    today: 'วันนี้',
    yesterday: 'เมื่อวาน',
    last7Days: '7 วันที่ผ่านมา',
    last14Days: '14 วันที่ผ่านมา',
    last30Days: '30 วันที่ผ่านมา',
    lastMonth: 'เดือนที่แล้ว',
    lifeTime: 'ระยะเวลาในการใช้งาน',
    thisWeek: 'สัปดาห์นี้',
    thisMonth: 'เดือนนี้',
  },
  errorMessage: {
    dateInvalid: '',
    inputInvalid: 'กรุณาใส่ข้อมูลการค้นหา',
    selectInvalid: 'โปรดเลือกรายการ',
  },
  importData: {
    error: {
      required: '{{fieldName}}จะต้องอยู่ในแถว {{rowNumber}}.',
      transient: '{{message}} ในแถว {{rowNumber}}.',
      invalidWField: '{{fieldName}} {{message}} ในแถว {{rowNumber}}',
      invalidNoField: '{{message}} ในแถว {{rowNumber}}',
      notExist: 'ค่าที่ให้ไว้สำหรับ {{fieldName}}ไม่มีอยู่ใน {{rowNumber}} ',
    },
  },
  leadDetailFields: {
    year: 'ปี',
    brand: 'ยี่ห้อ',
    model: 'รุ่น',
    sumInsured: 'ทุนประกัน',
    engineSize: 'ขนาดเครื่องยนต์',
    engineNumber: 'หมายเลขเครื่องยนต์',
    transmission: 'เกียร์รถยนต์',
    dashCam: 'กล้องติดรถยนต์',
    purpose: 'วัตถุประสงค์',
    province: 'จังหวัด',
    modification: 'การดัดแปลง',
    licensePlate: 'ทะเบียนรถ',
    gender: 'เพศ',
    dob: 'วันเกิด',
    age: 'อายุ',
    city: 'เมือง',
    leadType: 'ประเภทลีด',
    leadId: 'รหัสลีด',
    reference: 'อ้างอิง',
    redPlate: 'ป้ายแดง',
    firstName: 'ชื่อจริง',
    lastName: 'นามสกุล',
    'tax/companyTax': 'ภาษี/ภาษีบริษัท',
    nationalId: 'บัตรประจำตัวประชาชน',
    company: 'บริษัท',
    commLanguage: 'คอม ภาษา',
    title: 'หัวข้อ',
    orderType: 'ประเภทการสั่งซื้อ',
    customerId: 'รหัสลูกค้า',
    renewalId: 'รหัสลีดต่ออายุ',
    orderId: 'เลขออเดอร์',
    team: 'ทีม ',
    supervisor: 'ซุปเปอร์ไวเซอร์',
    salesAgent: 'เซลล์เอเจ้นท์ ',
    drivingPurpose: 'วัตถุประสงค์ในการขับขี่',
    firstDriverName: 'ชื่อผู้ขับที่ 1',
    firstDriverDOB: 'วันเกิดผู้ขับที่ 1',
    secondDriverName: 'ชื่อผู้ขับที่ 2',
    secondDriverDOB: 'วันเกิดผู้ขับที่ 2',
    agentName: 'เอเจนท์',
    noOfDoor: 'จำนวนประตู',
    cabType: 'ประเภทแคป',
    voluntaryPolicyStartDate: 'เริ่มคุ้มครองกรมธรรม์ภาคสมัครใจ',
    compulsoryPolicyStartDate: 'เริ่มคุ้มครองพรบ.',
  },
  logoutOption: {
    selectStatus: 'เลือกสถานะ',
    lunch: 'พักกลางวัน',
    coffee: 'พักดื่มกาแฟ',
    training: 'การฝึกอบรม',
    meeting: 'ประชุม',
    toilet: 'เข้าห้องน้ำ',
    dayend: 'เลิกงาน',
  },
  emailTemplateOption: {
    quote: {
      title:
        'แรบบิท ไฟแนนซ์: กรุณายืนยันคำสั่งซื้อแพ็กเกจประกันภัยราคาพิเศษของคุณ {{leadId}}',
      content:
        'เรียน คุณลูกค้าที่เคารพ ขอขอบคุณที่ไว้วางใจแรบบิทไฟแนนซ์ เว็บไซต์ด้านประกันภัยและการเงินออนไลน์ที่ใหญ่ที่สุดในประเทศไทย เราขอรับประกันว่าได้มอบราคาที่ดีที่สุดในท้องตลาดเพื่อคุณลูกค้าโดยเฉพาะ \n\n[[url]] \n\nโปรดตรวจสอบใบเสนอราคาประกันภัยรถยนต์ คำสั่งหมายเลข:{{leadId}} พร้อมด้วยรายละเอียดความคุ้มครอง ที่เราได้แนบมาในอีเมลฉบับนี้ \n\nหากคุณต้องการซื้อ หรือมีข้อสงสัยเกี่ยวกับแพ็กเกจนี้ โปรดแจ้งเจ้าหน้าที่ของเรา ด้วยการตอบกลับอีเมลฉบับนี้ \n\nด้วยความเคารพอย่างสูง, \n\nแรบบิทไฟแนนซ์',
    },
    paymentFollowUp: {
      title: 'แรบบิท ไฟแนนซ์: ยืนยันออเดอร์ เลขที่ออเดอร์ {{leadId}}',
      content:
        'ขอขอบคุณที่ไว้วางใจแรบบิทไฟแนนซ์ เว็บไซต์ด้านประกันภัยและการเงินออนไลน์ที่ใหญ่ที่สุดในประเทศไทย เราขอรับประกันว่าได้มอบราคาที่ดีที่สุดในท้องตลาดเพื่อคุณลูกค้าโดยเฉพาะ \n\nกรุณาตรวจสอบใบยืนยันการสั่งซื้อและใบแจ้งราคาสินค้า \n\nแพคเกจ:{{purchasePackage}} \n\nในขั้นตอนต่อไป , โปรดชำระเงินโดยเลือกหนึ่งในตัวเลือกการชำระเงินของเรา: \n\n[ตัวเลือกการชำระเงิน] \n\nหลังจากการชำระเงินเสร็จสิ้น เราจะมอบสำเนากรมธรรม์ประกันภัยรถยนต์ชั่วคราวแบบดิจิทัลให้คุณลูกค้าทางอีเมล และจะนำส่งกรมธรรม์ประกันภัยฉบับจริงให้คุณลูกค้าโดยเร็วที่สุด \n\nด้วยความเคารพอย่างสูง, \n\nแรบบิทไฟแนนซ์',
    },
    notReachable: {
      title: 'แรบบิท ไฟแนนซ์: {{leadId}} ไม่สามารถติดต่อได้',
      content:
        'ขอขอบคุณที่ไว้วางใจแรบบิทไฟแนนซ์ เว็บไซต์ด้านประกันภัยและการเงินออนไลน์ที่ใหญ่ที่สุดในประเทศไทย เราขอรับประกันว่าได้มอบราคาที่ดีที่สุดในท้องตลาดเพื่อคุณลูกค้าโดยเฉพาะ เราไม่สามารถติดต่อคุณเพื่อสอบถามรายละเอียดเพิ่มเติมเกี่ยวกับประกันภัยรถยนต์ของคุณได้ \n\nกรุณาติดต่อเจ้าหน้าที่แรบบิทไฟแนนซ์ได้ที่ 02-022-1222 ตลอดเวลาทำการ หรือทาง LINE: @rabbitfinance \n\nขอขอบคุณคุณลูกค้าสำหรับความร่วมมือ \n\nด้วยความเคารพอย่างสูง, \n\nแรบบิทไฟแนนซ์',
    },
    renewalReminder: {
      title: '',
      content:
        'Hi Alex \n\nThanks for using our product. We’re really sad to see you go – but we had a good run. \n\nIf you have any outstanding questions, feel free to contact us at support@acme.com or +123456789. \n\nAnd, if you ever need a product like ours in future, we hope we’ll see you again. \n\nAll the best,',
    },
    noTemplate: {
      title: '',
      content: '',
    },
  },
  team: {
    admin: 'แอดมิน',
    manager: 'ผู้จัดการ',
    sales: 'เซลล์เอเจ้นท์',
    supervisor: 'ซุปเปอร์ไวเซอร์',
    inbound: 'อินบาวด์เอเจ้นท์',
    customerService: 'บริการลูกค้า',
    documentsCollection: 'รวบรวมเอกสาร',
    qualityControl: 'ตรวจสอบคุณภาพ',
    submission: 'แจ้งงาน',
  },
  weekDay: {
    mon: 'จันทร์',
    tue: 'อังคาร',
    wed: 'พุธ',
    thu: 'พฤหัส',
    fri: 'ศุกร์',
    sat: 'เสาร์',
    sun: 'อาทิตย์',
  },
  searchFieldLeadOption: {
    customerName: 'ชื่อลูกค้า',
    customerPhone: 'โทรศัพท์ลูกค้า',
    customerEmail: 'อีเมลลูกค้า',
    id: 'ไอดี',
  },
  dateTypeLeadOption: {
    createOn: 'สร้างขึ้นเมื่อ',
    updateOn: 'อัปเดตเมื่อ',
    assignOn: 'มอบหมายเมื่อ',
    rejectOn: 'ถูกปฏิเสธเมื่อ',
    policyStartOn: 'กรมธรรม์เริ่มต้นเมื่อ',
    policyExpiryOn: 'กรมธรรม์หมดอายุเมื่อ',
  },
  dateType: {
    createdOn: 'สร้างขึ้นเมื่อ',
    updatedOn: 'อัปเดตเมื่อ',
  },
  leadTypeFilter: {
    new: 'ใหม่',
    retainer: 'รีเทนเนอร์',
    renewal: 'ต่ออายุ',
  },
  leadStatus: {
    new: 'ใหม่',
    valid: 'สมบูรณ์',
    contacted: 'ติดต่อแล้ว',
    interested: 'สนใจ',
    prospect: 'มีโอกาสซื้อ',
    purchased: 'ซื้อ',
    pendingPayment: 'รอการชำระเงิน',
    cancelled: 'ยกเลิก',
  },
  rejectReason: {
    wrongNumber: 'เบอร์ไม่ถูกต้อง: ไม่ใช่เจ้าของรถ',
    cantContact: 'เบอร์โทรศัพท์ใช้งานไม่ได้',
    noCar: 'ไม่มีรถ',
    dontCall: 'ไม่ให้ติดต่ออีก',
    notExpiring: 'ไม่อยู่ในระยะเวลาหมดอายุกรมธรรม์ 90 วัน',
    purchasedFromOther: 'Already purchase insurance from other insurer',
    purchasedFromRabbit: 'Already purchase insurance from Rabbit Finance',
  },
  statusCollection: {
    active: 'ใช้งาน',
    inactive: 'ไม่ใช้งาน',
  },
  insuranceTypes: {
    type1: 'ประเภท 1',
    type2: 'ประเภท 2',
    type2Plus: 'ประเภท 2+',
    type3: 'ประเภท 3',
    type3Plus: 'ประเภท 3+',
    mandatory: 'พ.ร.บ.',
  },
  leadSourceTypes: {
    online: 'ออนไลน์',
    offline: 'ออฟไลน์',
  },
  autoAssignOption: {
    all: 'ทั้งหมด',
    yes: 'ใช่',
    no: 'ไม่',
  },
  hideOption: {
    yes: 'ใช่',
    no: 'ไม่',
  },
  statusOptions: {
    active: 'ใช้งาน',
    suspended: 'ถูกระงับ',
  },
  importFileStatus: {
    complete: 'Success',
    inProgress: 'In progress',
    error: 'Failed',
  },
  productionOptions: {
    carInsurance: 'ประกันภัยรถยนต์',
  },
  api: {
    'roles/admin': 'แอดมิน',
    'roles/manager': 'ผู้จัดการ',
    'roles/supervisor': 'ซุปเปอร์ไวเซอร์',
    'roles/sales': 'เซลล์เอเจ้นท์ ',
    'roles/inbound': 'อินบาวด์เอเจ้นท์',
    'roles/customer-service': 'บริการลูกค้า',
    'roles/documents-collection': 'รวบรวมเอกสาร',
    'roles/quality-control': 'ตรวจสอบคุณภาพ',
    'roles/submission': 'แจ้งงาน',
    'roles/problem-case': 'Problem Case',
  },
  qcStatus: {
    preApproved: 'Pre-Approved',
    criticalIssues: 'Critical Issues',
    issuesFixed: 'Issues Fixed',
  },
  statusOption: {
    preSubmitted: 'Pre-Submitted',
  },
  approveStatus: {
    endorsement: 'Endorsement',
    otherProblems: 'Other Problems',
  },
  menu: {
    lead: {
      root: 'ลีด',
      assignment: 'มอบหมายลีด',
      rejections: 'ยกเลิกลีด',
      all: 'ลีดทั้งหมด',
      import: 'นำเข้าลีด',
      distribution: 'กระจายลีด',
      sources: 'แหล่งที่มาของลีด',
      scoring: 'คะแนนลีด',
      overflow: 'ภาพรวมการทำงาน',
      segmentation: 'การแบ่งกลุ่ม',
    },
    order: {
      root: 'ออเดอร์',
      all: 'ออเดอร์ทั้งหมด',
      documents: 'เอกสารออเดอร์',
      QC: 'ตรวจสอบออเดอร์',
      submission: 'การส่งมอบออเดอร์',
      approval: 'อนุมัติออเดอร์',
    },
    userManagement: {
      root: 'การจัดการผู้ใช้งาน',
      users: 'ผู้ใช้งาน',
      teams: 'ทีม',
    },
    package: {
      root: 'แพคเกจ',
      search: 'ค้นหาแพคเกจ',
      import: 'นำเข้าแพคเกจ',
    },
    carDiscount: {
      root: 'นำเข้าส่วนลดรถยนต์',
    },
  },
  titleTag: {
    orderAll: 'All Orders | Order Management',
    orderDocument: 'Documents Module | Order Management',
    orderQC: 'QC Module | Order Management',
    orderSubmission: 'Submission Module | Order Management',
    orderApproval: 'Approval Module | Order Management',
  },
  orderUpdateFrm: {
    pending: 'Documents pending',
    missing: 'Start submission with missing documents',
    complete: 'Documents complete',
    submission: 'Cannot collect documents in time for submission',
    warning: 'Missing information:',
    commentLbl: 'Comment',
    commentPlaceholder: 'All documents received.',
  },
  customQuote: {
    packageTypes: {
      standard: 'แพคเกจใหม่',
      renewal: 'แพคเกจต่ออายุ',
      transfer: 'แพคเกจโอนโค้ด',
    },
  },
  shortInsurers: {
    1: 'อลิอันซ์ ซี.พี.',
    2: 'ไทยไพบูลย์ ประกันภัย',
    3: 'ไอโออิ กรุงเทพประกันภัย',
    4: 'เอเชีย ประกันภัย',
    5: 'สินทรัพย์ประกันภัย',
    6: 'แอกซ่า ประกันภัย',
    7: 'กรุงเทพประกันภัย',
    8: 'เจ้าพระยาประกันภัย',
    9: 'จรัญประกันภัย',
    10: 'เทเวศประกันภัย',
    11: 'ทิพยประกันภัย',
    12: 'เอราวัณประกันภัย',
    13: 'อินทรประกันภัย',
    14: 'กมลประกันภัย',
    15: 'เคเอสเค ประกันภัย',
    16: 'มิตรแท้ประกันภัย',
    17: 'เมืองไทยประกันภัย',
    18: 'นำสินประกันภัย',
    19: 'อาคเนย์ประกันภัย',
    20: 'สินมั่นคงประกันภัย',
    21: 'ไทยประกันภัย',
    22: 'สยามซิตี้ ประกันภัย',
    23: 'ไทยเศรษฐกิจประกันภัย',
    24: 'ไทยศรีประกันภัย',
    25: 'ไทยวิวัฒน์ประกันภัย',
    26: 'โตเกียวมารีนประกันภัย',
    27: 'วิริยะประกันภัย',
    28: 'ธนชาตประกันภัย',
    29: 'สามัคคีประกันภัย',
    30: 'เจนเนอราลี่ ประกันภัย',
    31: 'นวกิจประกันภัย',
    32: 'กรุงไทยพานิชประกันภัย',
    33: 'แอลเอ็มจี ประกันภัย',
    34: 'เอ็ม เอส ไอ จี ประกันภัย',
    35: 'คุ้มภัยโตเกียวมารีนประกันภัย',
    36: 'ศรีอยุธยา เจนเนอรัล ประกันภัย',
    37: 'เอไอจี ประกันภัย',
    38: 'รู้ใจ',
    40: 'ชัปป์',
    42: 'เอฟพีจี',
  },
  longInsurers: {
    1: 'บริษัท อลิอันซ์ ประกันภัย จำกัด (มหาชน)',
    2: 'บจม.ไทยไพบูลย์ ประกันภัย',
    3: 'ไอโออิ กรุงเทพประกันภัย จำกัด (มหาชน)',
    4: 'บริษัท เอเชียประกันภัย (1950) จำกัด (มหาชน)',
    5: 'สินทรัพย์ประกันภัย จำกัด (มหาชน)',
    6: 'บริษัท  แอกซ่าประกันภัย จำกัด (มหาชน)',
    7: 'บริษัท กรุงเทพประกันภัย จำกัด (มหาชน)',
    8: 'เจ้าพระยาประกันภัย จำกัด (มหาชน)',
    9: 'จรัญประกันภัย จำกัด (มหาชน)',
    10: 'บริษัท เทเวศประกันภัย จำกัด (มหาชน)',
    11: 'บริษัท ทิพยประกันภัย จำกัด (มหาชน)',
    12: 'เอราวัณประกันภัย จำกัด',
    13: 'อินทรประกันภัย จำกัด(มหาชน)',
    14: 'กมลประกันภัย จำกัด (มหาชน)',
    15: 'บริษัท เคเอสเค ประกันภัย (ประเทศไทย) จำกัด (มหาชน)',
    16: 'มิตรแท้ประกันภัย จำกัด (มหาชน)',
    17: 'บริษัท เมืองไทยประกันภัย จำกัด (มหาชน)',
    18: 'นำสินประกันภัย จำกัด (มหาชน)',
    19: 'บริษัท อาคเนย์ประกันภัย จำกัด ( มหาชน )',
    20: 'บริษัท สินมั่นคงประกันภัย จำกัด (มหาชน)',
    21: 'ไทยประกันภัย จำกัด (มหาชน)',
    22: 'บจม.สยามซิตี้ ประกันภัย',
    23: 'ไทยเศรษฐกิจประกันภัย จำกัด (มหาชน)',
    24: 'ไทยศรีประกันภัย จำกัด (มหาชน)',
    25: 'บริษัทประกันภัยไทยวิวัฒน์ จำกัด (มหาชน)',
    26: 'บริษัท โตเกียวมารีนประกันภัย (ประเทศไทย) จำกัด(มหาชน)',
    27: 'บริษัท วิริยะประกันภัย จำกัด (มหาชน)',
    28: 'บริษัท ธนชาตประกันภัย จำกัด (มหาชน)',
    29: 'บริษัท สามัคคีประกันภัย จำกัด (มหาชน)',
    30: 'บริษัท เจนเนอราลี่ ประกันภัย (ไทยแลนด์) จำกัด (มหาชน)',
    31: 'บริษัท นวกิจประกันภัย จำกัด (มหาชน)',
    32: 'กรุงไทยพานิชประกันภัย จำกัด (มหาชน)',
    33: 'บริษัท แอลเอ็มจี ประกันภัย จำกัด',
    34: 'บริษัท เอ็ม เอส ไอ จี ประกันภัย (ประเทศไทย) จำกัด (มหาชน)',
    35: 'บมจ. คุ้มภัยโตเกียวมารีนประกันภัย (ประเทศไทย) ',
    36: 'บริษัท ศรีอยุธยา เจนเนอรัล ประกันภัย จำกัด (มหาชน)',
    37: 'เอไอจี ประกันภัย (ประเทศไทย) จำกัด (มหาชน)',
    38: 'รู้ใจ ประกันภัย',
    40: 'บริษัท ชับบ์สามัคคีประกันภัย จำกัด (มหาชน)',
    42: 'เอฟพีจี ประกันภัย',
  },
  motoType: {
    type1: 'Type 1',
    type2: 'Type 2',
    type2Plus: 'Type 2+',
    type3: 'Type 3',
    type3Plus: 'Type 3+',
  },
};
