export const ImportLeadMock = [
  {
    id: 1,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: 'Source',
    status: 'In progress',
  },
  {
    id: 2,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: 'Source',
    status: 'In progress',
  },
  {
    id: 3,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: 'Source',
    status: 'In progress',
  },
  {
    id: 4,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: 'Source',
    status: 'In progress',
  },
  {
    id: 5,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },

  {
    id: 6,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 7,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 8,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 9,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 10,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 11,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 12,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 13,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 14,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 15,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 16,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
];

export const ImportLeadSortMock = [
  {
    id: 1,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: 'Source',
    status: 'In progress',
  },
  {
    id: 2,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 3,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: 'Source',
    status: 'In progress',
  },
  {
    id: 4,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: 'Source',
    status: 'In progress',
  },
  {
    id: 5,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },

  {
    id: 6,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 7,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 8,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 9,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 10,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 11,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 12,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 13,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 14,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 15,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
  {
    id: 16,
    sequence: '1 (best)',
    importedBy: 'Siriwan',
    importedOn: '02/08/2020(5:13:39PM)',
    product: 'Car Insurance',
    leadRecord: 100,
    source: '100',
    status: 'In progress',
  },
];
