steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args: ["build", "--build-arg", "YARN_BUILD_ENV=$_YARN_BUILD_ENV", "-t", "$_IMAGE_NAME:$COMMIT_SHA", "..", "-f", "$_DOCKERFILE_NAME"]
    dir: $_DOCKERFILE_DIR

  - id: Push
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE_NAME:$COMMIT_SHA"]

  - id: Kustomize
    name: asia.gcr.io/$PROJECT_ID/kustomize
    entrypoint: sh
    args:
      - '-c'
      - |-
        if [ "$_KUSTOMIZE_OVERLAY" != "" ]; then
          /builder/envsubst-kustomize.sh "$_KUSTOMIZE_ENVSUBST_TARGET" build $_KUSTOMIZE_OVERLAY --output $_K8S_YAML_PATH
        fi
    env:
      - BRANCH_NAME=$BRANCH_NAME

  - id: Prepare deploy
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--output=output'

  - id: Save configs
    name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi    
    entrypoint: sh

  - id: Apply deploy
    name: gcr.io/cloud-builders/gke-deploy
    args: ["apply", "--filename=output/expanded", "--cluster=$_GKE_CLUSTER", "--location=$_GKE_LOCATION", "--namespace=$_K8S_NAMESPACE"]

options:
  substitutionOption: ALLOW_LOOSE
  machineType: N1_HIGHCPU_8
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
timeout: 900s
