name: 'Close stale PRs'
on:
  schedule:
    - cron: '5 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'This PR is stale because it has been open 5 days with no activity. Remove stale label or comment or this will be closed in 3 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 3 days with no activity.'
          days-before-pr-stale: 5
          days-before-pr-close: 3
